name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build .exe using PyInstaller
        run: |
          pyinstaller --onefile image_renamer.py

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/image_renamer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
